name: 'File Structure Diagnostic'

on:
  workflow_dispatch:

jobs:
  diagnose-structure:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out the repository's code
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. This step will show us the exact location of all your files
      - name: Show Current Directory and List All Files
        run: |
          echo "The current working directory is:"
          pwd
          echo "-------------------------------------------"
          echo "Listing all files and directories found:"
          ls -laR
          echo "-------------------------------------------"

      # 3. This step will test for the python script's location and tell us the result
      - name: Attempt to locate the python script
        run: |
          if [ -f "connect-counter/check_cameras.py" ]; then
            echo "SUCCESS: Found the script at 'connect-counter/check_cameras.py'"
          else
            echo "::error::FAILURE: Could NOT find the script at 'connect-counter/check_cameras.py'"
            exit 1
          fi

