name: 'Check Camera Count version 2.0'

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * 1'

jobs:
  check-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to push changes
    steps:
      # 1. Checks out the repository's code with full history
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # A full history is needed to reset and push correctly
          fetch-depth: 0

      # 2. Force sync with the remote branch to prevent divergence
      - name: Reset local branch to match remote
        run: git reset --hard origin/main

      # 3. Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. Installs Python packages and browsers
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      # 5. Installs system dependencies for Playwright
      - name: Install Playwright browser dependencies
        run: playwright install-deps

      # 6. Runs the script to update the CSV
      - name: Run camera check script
        run: python connect-counter/check_cameras.py

      # 7. Commits and pushes the updated CSV if changes are detected
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated log: Update camera count"
          file_pattern: connect-counter.csv
          branch: main

