name: 'Check Camera Count'

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * *'

jobs:
  check-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to push changes
    steps:
      # 1. Checks out the repository's code
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This is crucial for pulling and pushing correctly
          fetch-depth: 0

      # 2. Pull the latest changes from the main branch to avoid divergence
      - name: Pull latest changes
        run: git pull origin main

      # 3. Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. Installs Python packages for the script
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      # 5. Installs the required system dependencies for Playwright browsers
      - name: Install Playwright browser dependencies
        run: playwright install-deps

      # 6. Runs the script from the correct, verified path
      - name: Run camera check script
        run: python connect-counter/check_cameras.py

      # 7. Commits the updated CSV file if there are changes
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated log: Update camera count"
          file_pattern: connect-counter.csv
          branch: main

