name: 'Check Camera Count'

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * *'

jobs:
  check-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to push changes
    steps:
      # 1. Checks out the repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      # 4. Runs the script to update the CSV file
      - name: Run camera check script
        # This is the corrected line:
        # - It points to the script inside the 'connect-counter' folder.
        # - It REMOVES '>> connect-counter.csv'
        run: python connect-counter/check_cameras.py

      # 5. Safely commits the updated CSV file
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated log: Update camera count"
          file_pattern: connect-counter.csv
          branch: main

