name: 'Check Camera Count'

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * *'

jobs:
  check-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to push changes
    steps:
      # 1. Checks out the repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. --- NEW STEP ---
      # Verify that the script exists at the expected path before doing anything else.
      # If this step fails, the file is not in the correct location in the repo.
      - name: Verify script file exists
        run: |
          if [ ! -f "connect-counter/check_cameras.py" ]; then
            echo "::error::Script file not found at 'connect-counter/check_cameras.py'. Aborting workflow."
            echo "Please ensure the file exists at this exact path in your repository."
            exit 1
          else
            echo "Script file found. Proceeding with setup."
          fi

      # 3. Sets up Python (only runs if the check above passes)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install
          
      # 5. Install OS dependencies for Playwright
      - name: Install Playwright browser dependencies
        run: playwright install-deps

      # 6. Runs the script to update the CSV file
      - name: Run camera check script
        run: python connect-counter/check_cameras.py

      # 7. Safely commits the updated CSV file
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated log: Update camera count"
          file_pattern: connect-counter.csv
          branch: main

